### ISSUE TITLE
Threads Locking Terminal

### ISSUE THREAD

**Issue by patjbaum** [adamdachenhausen/cs330FinalProject#8]
https://github.com/adamdachenhausen/cs330FinalProject/blob/c68d69f8751c219192688a4b4b6355db032c7995/memSim.java#L33

After the call to initialUserPrompt(), the threads of the other objects don't allow the memSim object in the following while loop to print the next prompt. 

@jteresco

**Comment by jteresco** [comment]
Is your thread started somewhere?
